####################################################
#            Sentiment Bot Configuration           #
####################################################
#                  sentiment-bot                   #
# https://github.com/behaviorbot/sentiment-bot     #
####################################################
sentimentBotToxicityThreshold: .7
sentimentBotReplyComment: >
  Reveja nosso [código de conduta](code-of-conduct.md), em especial sobre respeito.

  O humano @Nereare revisará isto em breve.
